version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:RELEASE.2023-05-18T00-05-36Z
  command: server /data1 /data2 --console-address ":9001"
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: H55A7vwm6kC6zUCp
  networks:
    - minio
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio:
    <<: *minio-common
    hostname: minio
    volumes:
      - data1:/data1
      - data2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx-1-2.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "19000:9000"
      - "19001:9001"
    depends_on:
      - minio

    networks:
      - minio

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1:
    name: data1
    driver: local
    driver_opts:
      type: none
      device: /da1/data1
      o: bind
  data2:
    name: data2
    driver: local
    driver_opts:
      type: none
      device: /da1/data2
      o: bind

networks:
  minio:
    driver: bridge
